# Setup
title:               Julius P. J. Krebbekx
tagline:             'Personal Webpage'
description:         PhD student in control theory and engineering. Mathematician and physicist by training
url:                 http://krebbekx.github.io
baseurl:             ''
paginate:            5
#paginate_path:       "/blog/page:num/"
permalink:           pretty
domain:              krebbekx.github.io
baseurl:             /

# About/contact
author:
  name:              Julius P.J. Krebbekx
  url:               
  email:             j.p.j.krebbekx@tue.nl

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Custom vars
version:             1.0
google_analytics_id: #noting
